### ISSUE TITLE
Sucks at line breaks

### ISSUE THREAD

**Issue by elifoster** [retep998/ircbutt-rs#9] opened 2017-06-28 01:02 UTC
You can put multiple lines in the upload changes summary. For example, I uploaded new versions of `Tilesheet W 16.png` and `Tilesheet W 32.png` with the following summary:
```
Add spawn eggs: 
* Guard 
* Hellhound 
* Lilith 
* Lost Soul 
* Reflection 
* Shade of Leonard 
* Winged Monkey
```

however it was listed in #ftb-wiki-recentchanges as:
```
[17:58:11] <+BunnyButt> [upload] TheSatanicSanta uploaded a new version of File:Tilesheet W 16.png (Add spawn eggs:
[17:58:38] <+SatanicSanta> LOL
[17:59:22] <+BunnyButt> [upload] TheSatanicSanta uploaded a new version of File:Tilesheet W 32.png (Add spawn eggs:
```

The actual MediaWiki recent changes page condenses it all into one line like `Add spawn eggs: * Guard * Hellhound * Lilith * Lost Soul * Reflection * Shade of Leonard * Winged Monkey`.

**Comment by retep998** [comment] 2021-02-22 22:15
Theoretically this might be fixed now?

**Comment by SizableShrimp** [comment] 2021-02-23 07:41
Theoretically speaking, yes.

**Comment by retep998** [comment] 2021-02-23 08:13
Closing as unable to reproduce with current version, but feel free to reopen with more details if this issue comes up again.

**Closed as completed by retep998** 2021-02-23 08:13 UTC
Labels: bug
